# Generated by Django 3.0.14 on 2022-03-14 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('price', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Fecha de entrada')),
                ('departure_date', models.DateField(verbose_name='Fecha de salida')),
                ('n_guests', models.IntegerField(verbose_name='Invitados')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Teléfono')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('localizator', models.CharField(max_length=20, verbose_name='Localizador')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscadorReservas.Room')),
            ],
        ),
    ]
